Update dev-desktop install

diff --git a/dev-desktop b/dev-desktop
--- a/dev-desktop
+++ b/dev-desktop
@@ -1,270 +1,137 @@
 #!/bin/sh
 
-root="$HOME/.dev-desktop"
-shell_file="$HOME/.zshrc"
-config_file="$root/config"
+LOGFILE=~/.dev-desktop.log
+BREWFILE=./Brewfile
 
-source "$root/functions"
-source $config_file
-
-# Please coding here
-
-if ! test -d "$HOME/bin"; then
-  mkdir "$HOME/bin"
+if [ -e "$LOGFILE" ]; then
+    rm "$LOGFILE"
 fi
 
-# Install brew
+touch $LOGFILE
+
+source "./functions"
+
+title_echo "General"
+
+if [ ! -d "$HOME/bin" ]; then
+    progress_echo "Create bin directory"
+	mkdir "$HOME/bin"
+    success_echo
+fi
+
+title_echo "Homebrew"
+
 if ! command -v brew >/dev/null; then
-  fancy_echo "Installing Homebrew ..."
-  curl -fsS 'https://raw.githubusercontent.com/Homebrew/install/master/install' | ruby
-  append_to_file "$shell_file" 'export PATH="/usr/local/bin:$PATH"'
+  progress_echo "Installing Homebrew"
+  curl -fsS 'https://raw.githubusercontent.com/Homebrew/install/master/install' | ruby >> $LOGFILE
+  success_echo
 else
-  fancy_echo "Homebrew already installed. Skipping ..."
+  progress_echo "Updating"
+  brew update >> $LOGFILE 2>&1
+  success_echo
 fi
 
-fancy_echo "Updating Homebrew ..."
-cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update
+if [ -x /usr/local/bin/brew ]; then 
+    progress_echo "Check installation"
+    if brew doctor >> $LOGFILE 2>&1; then
+        success_echo "Your Homebrew installation is good to go"
+    else
+        fail_echo "Your Homebrew installation reported some errors or warnings, please review the Homebrew messages to see if any action is needed."
+    fi
 
-fancy_echo "Verifying the Homebrew installation..."
-if brew doctor; then
-  fancy_echo "Your Homebrew installation is good to go."
-else
-  fancy_echo "Your Homebrew installation reported some errors or warnings."
-  echo "Review the Homebrew messages to see if any action is needed."
+    if [ -e "$BREWFILE" ]; then
+        progress_echo "Install formulas and casks"
+
+        if brew bundle --file="$BREWFILE" >> $LOGFILE; then
+            success_echo "All formulas and casks were installed successfully"
+        else
+            fail_echo "Some formulas or casks failed to install"
+            message_echo "This is usually due to one of the Mac apps being already installed,"
+            message_echo "in which case, you can ignore these errors."
+        fi
+    fi
 fi
 
-fancy_echo "Installing formulas and casks from the Brewfile ..."
-if [ -e "$root/Brewfile" ]; then
-  if brew bundle --file="$root/Brewfile"; then
-    fancy_echo "All formulas and casks were installed successfully."
-  else
-    fancy_echo "Some formulas or casks failed to install."
-    echo "This is usually due to one of the Mac apps being already installed,"
-    echo "in which case, you can ignore these errors."
-  fi
-fi
+title_echo "Shell"
 
-# If zsh is not the default sh, change it
+progress_echo "Check zsh is the default shell"
 if [ $SHELL != "/bin/zsh" ]; then
-  fancy_echo "Setting ZSH as default shell ..."
-  chsh -s /bin/zsh
+    fail_echo
+    progress_echo "Set zsh as default shell"
+    chsh -s /bin/zsh
+    success_echo
 else
-  fancy_echo "ZSH is the default shell ..."
+    success_echo
 fi
 
-if [ ! -e "$config_file" ]; then
-  touch "$config_file"
+progress_echo "Configure ZSH"
+
+if [ ! -f ~/.zshrc ]; then
+    mv dotfiles/zshrc ~/.zshrc
 fi
 
-if [ ! -e "$shell_file" ]; then
-  fancy_echo "Creating a zsh profile ..."
-  touch "$shell_file"
+mv -f dotfiles/profile ~/.profile
+
+if [ -d ~/.powerlevel9k ]; then
+    mv -f ~/.powerlevel9k ~/.Trash/powerlevel9k
+fi
+
+mv -f dotfiles/powerlevel9k ~/.powerlevel9k
+
+success_echo
+
+if [ ! -f "$HOME/.ssh/id_rsa" ]; then
+  progress_echo "Configure SSH"
+  echo -n "\nYour email : "
+  read -r email
+  ssh-keygen -t rsa -b 4096 -C "$email"
+  success_echo
+fi
+
+progress_echo "Configure Git"
+mv -f dotfiles/gitconfig ~/.gitconfig
+success_echo
+
+title_echo "Development"
+
+## PHP
+
+message_echo "Check PHP version $(php -v | egrep 'PHP (\d{1,}\.?){2,3}' | awk '{ print $2 }')"
+progress_echo "Check PHP's package manager"
+brew_formula_php=$(brew list | egrep '^php(@(\d{1,}\.?){2})?$')
+
+if [ -z $brew_formula_php ]; then
+    message_echo "Apple"
 else
-  mv -f "$shell_file" "$shell_file-bak"
-  touch "$shell_file"
+    success_echo "Homebrew, formula $brew_formula_php installed"
 fi
 
-if [ ! -f "$HOME/.gemrc" ]; then
-  touch "$HOME/.gemrc"
-fi
+## Composer
 
-append_to_file "$HOME/.gemrc" 'gem: --no-document'
-
-if ! brew_is_installed "chruby"; then
-  fancy_echo 'Installing chruby, ruby-install, and the latest Ruby...'
-  brew install chruby
-  brew install ruby-install
-  ruby-install ruby
-
-  # Switch to latest
-  . /usr/local/share/chruby/chruby.sh
-  chruby "ruby-$(latest_installed_ruby)"
-fi
-
-# fancy_echo "Updating Rubygems ..."
-gem update --system
-#
-if ! gem_is_installed 'sass'; then
-  fancy_echo "Installing Sass ..."
-  gem install sass
-else
-  fancy_echo "Sass already installed. Skipping ..."
-fi
-
-# Install PHP
-current_version_php=$(brew list | egrep '^php\d{2}$')
-
-if [ ! -z $current_version_php ]; then
-  echo "The PHP version $current_version_php is installed."
-  prompt="Would you change the version ? "
-else
-  new_version_php=$(brew search php | cut -d'/' -f 3 | egrep '^php\d{2}$' | tail -n1)
-  echo "We will install $new_version_php"
-  prompt="Would you change the version to install ? "
-fi
-
-echo -n $prompt "[yn] "
-read -r -n 1 response_change_version
-
-if [ ! -z $response_change_version ] && ([ $response_change_version == 'y' ] || [ $response_change_version == 'Y' ]); then
-  echo ''
-  echo ''
-  echo 'Available versions : '
-  echo ''
-  brew search php | cut -d'/' -f 3 | egrep '^php\d{2}$'
-  echo ''
-  echo -n "Which version do you want to install ? "
-  read -r new_version_php
-
-  if [ ! -z $current_version_php ]; then
-    echo "Delete $current_version_php"
-    brew remove $current_version_php
-  fi
-fi
-
-if [ ! -z $new_version_php ]; then
-  fancy_echo "Installing PHP ..."
-  brew install $new_version_php
-elif [ ! -z $current_version_php ]; then
-  fancy_echo "PHP '$current_version_php' already installed. Skipping ..."
-fi
-
-# Install Composer
 if [ ! -e /usr/local/bin/composer ]; then
-  fancy_echo "Installing Composer ..."
-  expected_signature=$(wget -q -O - https://composer.github.io/installer.sig)
-  php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
-  actual_signature=$(php -r "echo hash_file('SHA384', 'composer-setup.php');")
+    progress_echo "Install composer"
+    EXPECTED_SIGNATURE="$(wget -q -O - https://composer.github.io/installer.sig)"
+    php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" >> $LOGFILE
+    ACTUAL_SIGNATURE="$(php -r "echo hash_file('SHA384', 'composer-setup.php');")"
 
-  if [ "$expected_signature" != "$actual_signature" ]; then
-    fancy_echo "ERROR: Invalid installer signature"
+    if [ "$EXPECTED_SIGNATURE" == "$ACTUAL_SIGNATURE" ]; then
+        php composer-setup.php --quiet >> $LOGFILE
+        mv composer.phar /usr/local/bin/composer
+        success_echo
+    else
+        >&2 echo 'ERROR: Invalid installer signature'
+        fail_echo
+    fi
+
     rm composer-setup.php
-    echo "Problem with the installer of the composer"
-    echo "Composer is not installed ..."
-  else
-    php composer-setup.php --quiet
-    rm composer-setup.php
-    mv composer.phar /usr/local/bin/composer
-  fi
 else
-  fancy_echo "Updating Composer ..."
-  composer selfupdate
+    progress_echo "Update composer"
+    @composer selfupdate >> $LOGFILE 2>&1
+    success_echo
 fi
 
-if [ ! -f "/usr/local/bin/symfony" ]; then
-  fancy_echo "Installing Symfony installer ..."
-  curl -LsS https://symfony.com/installer -o /usr/local/bin/symfony
-  chmod a+x /usr/local/bin/symfony
-else
-  fancy_echo "Updating Symfony installer ..."
-  symfony selfupdate
-fi
+## vim
 
-if ! test -f "/usr/local/etc/dnsmasq.conf"; then
-  # See https://passingcuriosity.com/2013/dnsmasq-dev-osx/
-  fancy_echo "Configuring Dnsmasq ..."
-
-  # Copy the default configuration file
-  cp $(brew list dnsmasq | grep /dnsmasq.conf.example$) /usr/local/etc/dnsmasq.conf
-  # Copy the daemon configuration file into place
-  sudo cp $(brew list dnsmasq | grep /homebrew.mxcl.dnsmasq.plist$) /Library/LaunchDaemons/
-  append_to_file "/usr/local/etc/dnsmasq.conf" "address=/local/127.0.0.1"
-
-  if ! test -d "/etc/resolver"; then
-    sudo mkdir -p /etc/resolver
-  fi
-
-  sudo tee /etc/resolver/local >/dev/null <<EOF
-nameserver 127.0.0.1
-EOF
-
-  # Start Dnsmasq automatically
-  sudo launchctl load /Library/LaunchDaemons/homebrew.mxcl.dnsmasq.plist
-fi
-
-if ! test -d "$HOME/.nvm"; then
-  mkdir "$HOME/.nvm"
-  export NVM_DIR="$HOME/.nvm"
-  . /usr/local/opt/nvm/nvm.sh
-  fancy_echo "Installing node ..."
-  nvm install node
-fi
-
-# Configure the git
-fancy_echo "Configuring your git ..."
-if [ -z "$git_config_user_name" ]; then
-  echo -n "Your name : "
-  read -r git_config_user_name
-  append_to_file "$config_file" "git_config_user_name=$git_config_user_name"
-fi
-
-if [ -z "$git_config_user_email" ]; then
-  echo -n "Your email : "
-  read -r git_config_user_email
-  append_to_file "$config_file" "git_config_user_email=$git_config_user_email"
-fi
-
-if ! command git config --get user.name "$git_config_user_name" > /dev/null ; then
-  git config --global user.name "$git_config_user_name"
-fi
-
-if ! command git config --get user.email $git_config_user_email > /dev/null ; then
-  git config --global user.email $git_config_user_email
-fi
-
-git config --global alias.co checkout
-git config --global alias.br branch
-git config --global alias.ci commit
-git config --global alias.st status
-git config --global alias.del-merged-branch '!git branch --merged | egrep -v "(\*|master|develop)" | xargs git branch -d'
-git config --global alias.cc '!git branch --merged | egrep -v "(\*|master|develop)" | xargs git branch -d'
-git config --global alias.edit-conflicted-files '!f() { git diff --name-status --diff-filter=U | cut -f2 ; }; $EDITOR `f`'
-git config --global alias.add-conflicted-files '!f() { git diff --name-status --diff-filter=U | cut -f2 ; }; git add `f`'
-
-if [ ! -d "$HOME/.ssh" ]; then
-  fancy_echo "Configuring your SSH ..."
-  ssh-keygen -t rsa -b 4096 -C "$git_config_user_email"
-fi
-
-fancy_echo "Configuring your zsh ..."
-
-append_to_file "$shell_file" 'source "/usr/local/share/antigen/antigen.zsh"'
-append_to_file "$shell_file" 'antigen use oh-my-zsh'
-append_to_file "$shell_file" 'antigen bundle git'
-append_to_file "$shell_file" 'antigen bundle zsh-users/zsh-syntax-highlighting'
-append_to_file "$shell_file" 'antigen bundle zsh-users/zsh-completions'
-append_to_file "$shell_file" 'antigen bundle symfony2'
-append_to_file "$shell_file" 'antigen bundle brew'
-append_to_file "$shell_file" 'antigen bundle docker'
-append_to_file "$shell_file" 'antigen bundle docker-compose'
-append_to_file "$shell_file" 'antigen theme https://github.com/denysdovhan/spaceship-zsh-theme spaceship'
-append_to_file "$shell_file" 'antigen apply'
-append_to_file "$shell_file" 'if test -e "$HOME/.profile"; then'
-append_to_file "$shell_file" '  source "$HOME/.profile"'
-append_to_file "$shell_file" 'fi'
-append_to_file "$shell_file" 'brew_path=$(brew --prefix)'
-append_to_file "$shell_file" 'export PATH="$HOME/bin:$HOME/.composer/vendor/bin:$brew_path/bin:$brew_path/sbin:$PATH"'
-append_to_file "$shell_file" 'export EDITOR="subl -w"'
-append_to_file "$shell_file" 'source /usr/local/share/chruby/chruby.sh'
-append_to_file "$shell_file" 'source /usr/local/share/chruby/auto.sh'
-append_to_file "$shell_file" "chruby ruby-$(latest_installed_ruby)"
-append_to_file "$shell_file" 'export NVM_DIR="$HOME/.nvm"'
-append_to_file "$shell_file" '. "/usr/local/opt/nvm/nvm.sh"'
-append_to_file "$shell_file" 'alias dev-desktop="bash <(curl -s https://raw.githubusercontent.com/laupiFrpar/dev-desktop/master/boot)"'
-append_to_file "$shell_file" "alias hostip=\"ifconfig | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(192\.([0-9]*\.){2}[0-9]*).*/\2/p'\""
-append_to_file "$shell_file" 'export HOST_IP=$(hostip)'
-
-fancy_echo "Configuring your vim ..."
-
-if ! test -f $HOME/.vimrc; then
-  touch $HOME/.vimrc
-fi
-
-append_to_file "$HOME/.vimrc" "set ruler"
-append_to_file "$HOME/.vimrc" "syntax on"
-
-if [ ! -d "$HOME/workspace" ]; then
-  mkdir "$HOME/workspace"
-fi
-
-fancy_echo 'All done!'
+progress_echo "Configure vim"
+mv -f dotfiles/vimrc ~/.vimrc
+success_echo
